name: personal_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  get: ^4.7.2
  flutter_animate: ^4.5.0
  animate_do: ^4.2.0
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/myicon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img2/
    - assets/img.jpeg